name: Test
on: [push]
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        java-version:
          - 8
          - 11
          - 17
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - name: Run tests
        run: ./gradlew allTests
  build:
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory:
          - examples/e2e
          - examples/jvm
          - examples/native
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build
        run: ./gradlew build
        working-directory: ${{ matrix.directory }}
  dokka:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository (master)
        uses: actions/checkout@v3
      - name: Clone Repository (gh-pages)
        run: git clone https://github.com/${{ github.repository }} -b gh-pages --depth 1 dokka || mkdir dokka
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: gradle
      - name: Build
        run: ./gradlew dokkaHtml
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dokka