name: Dokka
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository (master)
        uses: actions/checkout@v3
      - name: Clone Repository (gh-pages)
        run: git clone https://github.com/${{ github.repository }} -b gh-pages --depth 1 dokka || mkdir dokka
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: gradle
      - name: Build
        run: ./gradlew dokkaHtml
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dokka